# Generated by Django 4.1 on 2024-06-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musician", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="musician",
            name="age_gte_13",
        ),
        migrations.AddConstraint(
            model_name="musician",
            constraint=models.CheckConstraint(
                check=models.Q(("age__gte", 14)), name="age_gte_14"
            ),
        ),
    ]
